<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../../../Escritorio%20IRIS/Project1/xsd/SD_PAGO_ListaDevolucionesAEAT.wsdl"/>
      <rootElement name="EE_O_ListaDevolucionesAEAT" namespace="http://bphx.com/SD_PAGO_ListaDevolucionesAEAT"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="XSD">
      <schema location="../xsd/EE_PAGO_ListaDevolucionesAEAT.xsd"/>
      <rootElement name="EE_O_ListaDevolucionesAEAT" namespace="http://bphx.com/SD_PAGO_ListaDevolucionesAEAT"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.5.0(build 110418.1550.0174) AT [TUE MAR 28 16:07:09 CEST 2023]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:tns="http://bphx.com/SD_PAGO_ListaDevolucionesAEAT"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:sec="http://www.ruralserviciosinformaticos.com/XSD/SecurityHeader/"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ns0="http://www.ruralserviciosinformaticos.com/XSD/ErrorGenerico_O/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl tns sec xsd ns0 soap wsdl bpws xp20 mhdr bpel oraext dvm hwf med ids bpm xdk xref ora socket ldap">
  <xsl:template match="/">
    <tns:EE_O_ListaDevolucionesAEAT>
      <tns:Respuesta>
        <xsl:for-each select="/tns:EE_O_ListaDevolucionesAEAT/tns:Respuesta/tns:ListaDevolucionesAEAT[position() &lt;= /tns:EE_O_ListaDevolucionesAEAT/tns:Respuesta/tns:numeroRegistros]">
          <tns:ListaDevolucionesAEAT>
              <tns:codigoImpuestoAEAT>
                <xsl:value-of select="./tns:codigoImpuestoAEAT"/>
              </tns:codigoImpuestoAEAT>
              <tns:fechaEjecucion>
                <xsl:value-of select="./tns:fechaEjecucion"/>
              </tns:fechaEjecucion>
              <tns:tipoImpuesto>
                <xsl:value-of select="./tns:tipoImpuesto"/>
              </tns:tipoImpuesto>
              <tns:codigoModeloImpuesto>
                <xsl:value-of select="./tns:codigoModeloImpuesto"/>
              </tns:codigoModeloImpuesto>
              <tns:importe>
                <xsl:value-of select="./tns:importe"/>
              </tns:importe>
          </tns:ListaDevolucionesAEAT>
        </xsl:for-each>
      </tns:Respuesta>
    </tns:EE_O_ListaDevolucionesAEAT>
  </xsl:template>
</xsl:stylesheet>
